kind: pipeline
name: fonts-deploy

steps:
  - name: build fonts  
    image: node:10.15-alpine
    commands:
      - apk add --no-cache make gcc g++ python git
      - npm install
      - npm run build
  - name: publish releases
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_api_key
      files: __fonts/*